/**
 * scripts/seed-transactions.ts
 *
 * Drops the `transactions` collection and re-inserts dev fixtures from
 * scripts/fixtures/transactions.dev.json.
 *
 * Fixture entries use symbolic names for account, category, and member
 * which are resolved to real ObjectIds at runtime by querying the DB.
 * This makes fixtures stable across repeated `reset:dev` runs where all
 * ObjectIds are regenerated by migrations.
 *
 * Usage:  npm run seed:transactions
 *
 * Guards:
 *  - Blocked in NODE_ENV=production (unless FORCE_RESET=1).
 *  - Fails with a clear error if accounts/categories/members are missing
 *    (i.e. seed + migrate have not been run yet).
 */

import "dotenv/config";
import fs from "fs/promises";
import path from "path";
import { MongoClient, ObjectId } from "mongodb";

// ─── Types ────────────────────────────────────────────────────────────────────

interface FixtureEntry {
  localId?: string;            // optional stable key for parentRef cross-references
  account: string;             // account name  → resolved to accountId ObjectId
  category?: string | null;    // category name within account  → resolved to categoryId
  member?: string | null;      // member name  → resolved to paidByMemberId
  parentRef?: string | null;   // localId of parent entry  → resolved to parentTransactionId
  title: string;
  type: "income" | "expense";
  amountMinor: number;
  month: string;               // "YYYY-MM"  → Date(YYYY-MM-01T00:00:00Z)
  bookDate?: string | null;    // "YYYY-MM-DD" or null
  status: "booked" | "pending";
  isFromSharedAccount: boolean;
  notes?: string | null;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function parseJsonWithComments(txt: string): any {
  return JSON.parse(
    txt
      .replace(/^\uFEFF/, "")             // strip BOM if present
      .replace(/\/\*[\s\S]*?\*\//g, "")
      .replace(/^\s*\/\/.*$/gm, "")
  );
}

function toMonthDate(s: string): Date {
  const d = new Date(`${s}-01T00:00:00.000Z`);
  if (isNaN(d.getTime())) throw new Error(`Invalid month string: "${s}" (expected YYYY-MM)`);
  return d;
}

function toBookDate(s: string): Date {
  const d = new Date(`${s}T00:00:00.000Z`);
  if (isNaN(d.getTime())) throw new Error(`Invalid bookDate string: "${s}" (expected YYYY-MM-DD)`);
  return d;
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  if (process.env.NODE_ENV === "production" && process.env.FORCE_RESET !== "1") {
    console.error("[seed:transactions] Refusing to run in production without FORCE_RESET=1");
    process.exit(2);
  }

  const uri = process.env.MONGODB_URI ?? "mongodb://127.0.0.1:27017/tobu-finance";
  console.log("[seed:transactions] Connecting:", uri);
  const client = new MongoClient(uri);
  await client.connect();
  const db = client.db();

  try {
    // ── 1. Load fixture file ──────────────────────────────────────────────────
    const fixturePath = path.resolve("scripts/fixtures/transactions.dev.json");
    const raw = await fs.readFile(fixturePath, "utf-8");
    const fixtures: FixtureEntry[] = parseJsonWithComments(raw);

    // ── 2. Build lookup maps from current DB state ────────────────────────────
    const accounts = await db.collection("accounts")
      .find({}, { projection: { name: 1 } }).toArray();
    if (!accounts.length) {
      throw new Error("No accounts found. Run `npm run seed && npm run migrate` first.");
    }
    const accountByName = new Map<string, ObjectId>(
      accounts.map((a) => [a.name as string, a._id as ObjectId])
    );

    const categories = await db.collection("categories")
      .find({}, { projection: { name: 1, accountId: 1 } }).toArray();
    // Key: "AccountName|CategoryName" — disambiguates same-named cats across accounts
    const categoryByKey = new Map<string, ObjectId>();
    for (const cat of categories) {
      const acc = accounts.find((a) => String(a._id) === String(cat.accountId));
      if (acc) categoryByKey.set(`${acc.name}|${cat.name}`, cat._id as ObjectId);
    }

    const members = await db.collection("members")
      .find({}, { projection: { name: 1 } }).toArray();
    const memberByName = new Map<string, ObjectId>(
      members.map((m) => [m.name as string, m._id as ObjectId])
    );

    console.log(
      `[seed:transactions] Resolved: ${accounts.length} accounts, ` +
      `${categories.length} categories, ${members.length} members`
    );

    // ── 3. Pre-assign ObjectIds for every localId so parentRefs can be resolved
    const localIdToOid = new Map<string, ObjectId>();
    for (const f of fixtures) {
      if (f.localId) localIdToOid.set(f.localId, new ObjectId());
    }

    // ── 4. Validate and map each fixture to a DB document ────────────────────
    const now = new Date();
    const docs = fixtures.map((f, i) => {
      const label = f.localId ?? f.title ?? `index ${i}`;

      const accountId = accountByName.get(f.account);
      if (!accountId)
        throw new Error(`[fixture "${label}"] Account not found: "${f.account}"`);

      let categoryId: ObjectId | null = null;
      if (f.category) {
        categoryId = categoryByKey.get(`${f.account}|${f.category}`) ?? null;
        if (!categoryId)
          throw new Error(
            `[fixture "${label}"] Category not found: "${f.category}" in account "${f.account}"`
          );
      }

      let paidByMemberId: ObjectId | null = null;
      if (f.member) {
        paidByMemberId = memberByName.get(f.member) ?? null;
        if (!paidByMemberId)
          throw new Error(`[fixture "${label}"] Member not found: "${f.member}"`);
      }

      let parentTransactionId: ObjectId | null = null;
      if (f.parentRef) {
        parentTransactionId = localIdToOid.get(f.parentRef) ?? null;
        if (!parentTransactionId)
          throw new Error(
            `[fixture "${label}"] parentRef not found: "${f.parentRef}" ` +
            `(must match a localId defined earlier in the fixture file)`
          );
      }

      const _id = f.localId ? localIdToOid.get(f.localId)! : new ObjectId();

      return {
        _id,
        accountId,
        categoryId,
        title: f.title,
        notes: f.notes ?? null,
        type: f.type,
        amountMinor: f.amountMinor,
        month: toMonthDate(f.month),
        bookDate: f.bookDate ? toBookDate(f.bookDate) : null,
        status: f.status,
        isFromSharedAccount: f.isFromSharedAccount,
        paidByMemberId,
        parentTransactionId,
        recurrenceId: null,
        createdAt: now,
        updatedAt: now,
      };
    });

    // ── 5. Drop + re-insert ───────────────────────────────────────────────────
    const cols = await db.listCollections({ name: "transactions" }).toArray();
    if (cols.length) {
      await db.dropCollection("transactions");
      console.log("[seed:transactions] Dropped collection: transactions");
    }

    await db.collection("transactions").insertMany(docs, { ordered: true });

    const booked = docs.filter((d) => d.status === "booked").length;
    const pending = docs.filter((d) => d.status === "pending").length;
    const children = docs.filter((d) => d.parentTransactionId !== null).length;
    const parents = docs.filter((d) => d.parentTransactionId === null).length;
    console.log(
      `[seed:transactions] Inserted ${docs.length} transactions: ` +
      `${booked} booked, ${pending} pending | ` +
      `${parents} top-level, ${children} split-children`
    );
  } finally {
    await client.close();
    console.log("[seed:transactions] Done.");
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
